## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

- numpy = dataframe 행과 열로 구성
- 각각의 행 column = "series", 1차원 구조체
- 시리즈 여러개 == 데이터프레임

#### 2.1 Series와 DataFrame
Series

- series와 인덱스 함께 출력

In [ ]:
import pandas as pd
scores = pd.Series([90, 85, 88])
print(scores)
print(type(scores))

DataFrame

- 2차원(행, 열) 구조체
- 행 인덱스 + 열 이름 column

In [ ]:
data = {
    "이름": ["김철수", "이영희", "박민수"],  
    "부서": ["개발", "기획", "개발"],
    "급여": [4500, 5200, "4800"]
}

df = pd.DataFrame(data)
print(df) # 행 인덱스 0부터 시작 + column은 이름, 부서, 급여

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

- 탐색적 데이터 분석(EDA)
- `df.info()`
    - 누락치 확인(Non-Null Count)
    - dtype: 통계가 가능한 자료형인지 체크(잘못된 데이터가 있는지 여부 확인 -> 치환 -> 자료형 변환)

- `df.describe()`
    - 평균, 중앙값, 최대, 최소값을 통해서 이상치(극단치) 확인

In [ ]:
print("df.info()")
df.info() # info()를 통해 dtype 체크, object 존재시 통계 불가(숫자가 str으로 되어 있음)

In [ ]:
data = {
    "이름": ["김철수", "이영희", "박민수"],  
    "부서": ["개발", "기획", "개발"],
    "급여": [4500, 5200, 48000]
}

df = pd.DataFrame(data)

df.describe() # max값=이상치

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [ ]:
# df['급여'], type(df['급여'])

# 보너스 column 추가
df['보너스'] = df['급여'] * 0.1
df

In [ ]:
# 인덱스를 변경하는 경우
df_indexed = df.set_index('이름')
df_indexed

In [ ]:
# 변경한 인덱스를 다시 숫자형 인덱스로 초기화
df_restored = df_indexed.reset_index('이름')
df_restored # new dataframe
print(df_restored)
print(df is df_restored) # False

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

- axis: 0: -> 행 index 기준
- axis: 1: -> 열 index 기준

In [ ]:
df = pd.DataFrame({
    '중간고사': [80, 95, 70],
    '기말고사': [85, 90, 75] #인덱스 총 3개 (0, 1, 2)
}, index=['김철수', '이영희', '박민수']) # index=로 인덱스 설정 DataFrame({data dictionary}, index=[value 개수])

# df = df.set_index("김철수", "이영희", "박민수") DOESNT WORK

df

In [ ]:
# 각 시험별 (column에 대한) 평균 series 계산 -> axis=0. 행 기준(인덱스 기준)
score_means = df.mean(axis=0)
score_means

In [ ]:
means_per_student = df.mean(axis=1)
means_per_student

In [ ]:
score_gap = df.sub(score_means, axis=1) # 학생 실제 점수 - 시험 평균
score_gap

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택 (check location)

loc
- `.loc['행 label', [column label]]`: 행의 이름으로 검색(선택)
    - `.loc['행 label']`: 행만 검색 가능
    - `.loc['행 label', 'column label']` => numpy.자료형(검색 결과값)
    - `.loc[시작행:종료행, [컬럼1, 컬럼2, ...]]`
    - `'loc[..., 시작컬럼:종료컬럼]`

iloc
- `iloc[행 위치, 열 위치]`: 숫자 인덱스로 검색(선택)
    - loc와 사용 방법은 동일하지만 행 라벨이 아닌 **인덱스 번호**
    - 범위를 설정할 경우 종료 번호는 미만
    - ex) iloc[0:2, 0:2] -> 인덱스 0-1까지, 컬럼 0-1까지 ==> **숫자는 대부분 '미만'**

In [51]:
import pandas as pd

df = pd.DataFrame({
    '나이': [25, 30, 35, 40],
    '점수': [80, 95, 70, 85],
    '등급': ['B', 'A', 'C', 'B']
}, index = ['user1', 'user2', 'user3', 'user4'])

df

       나이  점수 등급
user1  25  80  B
user2  30  95  A
user3  35  70  C
user4  40  85  B

In [ ]:
df.loc['user1'], type(df.loc['user1'])

In [ ]:
df.loc['user1', '점수']

In [ ]:
df.loc['user1':'user4', ['점수', '등급']] # user1부터 user4까지 점수와 등급 검색

In [ ]:
df.loc['user1':'user2', '나이':'등급'] # user1부터 user2까지 나이부터 등급까지 검색

In [ ]:
df.iloc[0:2, 1:3] # iloc는 0:1까지, 1:2까지

#### 3.2 불리언 인덱싱과 query() 조건 검색

불리언 인덱싱 
- 조건에 해당하는 값만 T/F로 표기
- 컬럼별 값이 True인 조건만 찾아서 조회 가능
- & : and 연산 / 모두 참일 때 참
- | : or 연산 / 조건 중 하나만 참이어도 참

In [53]:
df

       나이  점수 등급
user1  25  80  B
user2  30  95  A
user3  35  70  C
user4  40  85  B

In [54]:
print(df['나이'] >= 30)
print(df['점수'] >= 80)

user1    False
user2     True
user3     True
user4     True
Name: 나이, dtype: bool
user1     True
user2     True
user3    False
user4     True
Name: 점수, dtype: bool

In [55]:
(df['나이'] >= 30) & (df['점수'] >= 80) # 두개 비교할 경우 각각 소괄호로 묶어주기

user1    False
user2     True
user3    False
user4     True
dtype: bool

In [ ]:
df[(df['나이'] >= 30) & (df['점수'] >= 80)]

query() 필터링

- 문자열 조건식 
- `@`로 외부 변수 참조 활용

In [52]:
df.query('나이 >= 30 and 점수 >= 80')

       나이  점수 등급
user2  30  95  A
user4  40  85  B

In [ ]:
# @ 사용 query()메서드 예시

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)

- 결측치 - np.nan, pd.NA, NONE


[결측치 확인]
- `df.info()` 확인
- `df.isna()`, `df.isnull()`
- `df.isna().sum()`: 컬럼별 결측치 총 개수
    - 기본값: `df.isna().sum(axis=0)` , 행 기준

In [ ]:
import numpy as np

raw_df = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': [pd.NA, 5, 6],
    'C': [7, 8, 9]
    })

print(raw_df)
print(raw_df.info()) # 결측치 확인

In [ ]:
print(True + True) # 2
print(False + 1) # 1

In [ ]:
print(raw_df.isna())
print("=" * 30)
print(raw_df.isnull())
print("=" * 30)
print(raw_df.isna().sum()) # 0 =>결측치 없음, 행 기준
print(raw_df.isna().sum(axis=1)) # 열 기준

3.3.2 결측치 삭제 (Drop)

- axis=0 : 행 기준 - 특정 행에 결측치가 있으면 제거 (기본)
- axis=1 : 열 기준 - 특정 열에 결측치가 있으면 제거 

- 열에서 결측 행만 삭제: `subset`

In [ ]:
print(raw_df.isna())

# 행 기준에서 결측치 삭제
raw_df.dropna() # 결측치가 있는 0, 1 행 삭제되어 2행만 남음

In [ ]:
# 열 기준에서 결측치 삭제
raw_df.dropna(axis=1)

In [ ]:
# subset

3.3.3 통계적 대푯값 대치 (Imputation)

대푯값 -> 데이터 손실 방지
- 평균값 : `mean()`
- 중앙값 : `median()` --> 극단치(이상치)의 영향을 덜 받음

대치
- `채워질data.fillna(채울data)`

In [ ]:
df_age = pd.DataFrame({
    '나이': [20, 25, None, 30, 95] # 극단치 95
    })

print(df_age)

median_val = df_age['나이'].median()
print("중앙값:", median_val) # 중앙값 27.5

df_age['나이'] = df_age['나이'].fillna(median_val)
print(df_age) # 2행 결측값이 중앙값으로 채워짐

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)

유사한 형식의 데이터가 근처에 있을 확률이 높으므로 직전 또는 직후의 유효한 값으로 결측치 대체

- `ffill()` : 앞쪽에 있는 값으로 대체
- `bfill()` : 뒤쪽에 있는 값으로 대체

In [ ]:
ts_df = pd.DataFrame({'온도': [18.2, None, None, 21.0]})
print(ts_df)

print("=" * 40)
# forward fill
print(ts_df.ffill())

print("=" * 40)
# backward fill
print(ts_df.bfill())

3.3.5 선형 보간법 (Linear Interpolation)

규칙이 있는 데이터일 경우, 유효 데이터의 변화율 계산하여 그에 따른 일정한 간격에 따라 결측치를 채움
- `df.interpolate(method='linear')`

In [ ]:
speed_df = pd.DataFrame({'속도': [10.0, None, None, 40.0]})

speed_df['속도'] = speed_df['속도'].interpolate(method='linear')

print(speed_df)

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)

- `.replace([이상한 값1, 이상한 값2, ...], pandas.NA)`: 이상한 데이터를 교체할 때, 이상한 값을 결측치(pandas.NA)로 변환

- `pandas.to_numeric(...)`: 숫자 자료형으로 변환

In [ ]:
import pandas as pd
survey_df = pd.DataFrame({'점수': [85, -999, '?', 95]})
survey_df.info()

In [ ]:
survey_df.describe()

In [ ]:
survey_df['점수'] = survey_df['점수'].replace([-999, '?'], pd.NA)
print(survey_df.info())

In [ ]:
survey_df['점수'] = pd.to_numeric(survey_df['점수'], errors='coerce')
survey_df.info()

In [49]:
survey_df.describe()

              점수
count   2.000000
mean   90.000000
std     7.071068
min    85.000000
25%    87.500000
50%    90.000000
75%    92.500000
max    95.000000

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)

ex) 미응답 여부 등 판단할 때 결측 여부 boolean column 자체를 생성
- `isna()` 활용

In [ ]:
user_df = pd.DataFrame({'소득': [300, None, 450, None]})

user_df['응답여부'] = user_df['소득'].isna()

print(user_df)

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환

- `.groupby(column)`
- `.mean(numeric_only=True)`
- `.to_numpy(dtype=numpy.자료형)`
    - to_다른 dataformat/type 가능

In [ ]:
import numpy as np


sales_df = pd.DataFrame({
    '지점': ['서울', '서울', '부산', '부산'],
    '매출': [100, 150, 80, 120]
})

sales_df

In [ ]:
grouped_df = sales_df.groupby('지점').mean(numeric_only=True) #그룹화 집계, numeric_only=True 필수

grouped_df

In [48]:
numpied = sales_df['매출'].to_numpy(dtype=np.float64) # DataFrame -> Numpy 배열 추출

numpied

array([100., 150.,  80., 120.])